// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEsOlHAD6FsTybvDLS5IETOev7LWUxxW8',
    appId: '1:352301693840:web:c1bf8e5bbd0b4924cf9115',
    messagingSenderId: '352301693840',
    projectId: 'cursors-design-business',
    authDomain: 'cursors-design-business.firebaseapp.com',
    storageBucket: 'cursors-design-business.appspot.com',
    measurementId: 'G-R0XRB2EM35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjPXDOa_VgbKPEwHjOw_S932aoqQRL4nw',
    appId: '1:352301693840:android:aab0b7b096587784cf9115',
    messagingSenderId: '352301693840',
    projectId: 'cursors-design-business',
    storageBucket: 'cursors-design-business.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhrqXJ6JB3RQI3s55z62PGsMk8XfW3O9o',
    appId: '1:352301693840:ios:dfbfcc21e05ee188cf9115',
    messagingSenderId: '352301693840',
    projectId: 'cursors-design-business',
    storageBucket: 'cursors-design-business.appspot.com',
    iosClientId: '352301693840-93i2qh3ooh3vg587tsgsf8rbri463gjn.apps.googleusercontent.com',
    iosBundleId: 'com.cursorsdesign.buesiness.csBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhrqXJ6JB3RQI3s55z62PGsMk8XfW3O9o',
    appId: '1:352301693840:ios:729ae80aef4c31eacf9115',
    messagingSenderId: '352301693840',
    projectId: 'cursors-design-business',
    storageBucket: 'cursors-design-business.appspot.com',
    iosClientId: '352301693840-iks4st1vulkv1enve3b5bo84mo55auss.apps.googleusercontent.com',
    iosBundleId: 'com.cursorsdesign.buesiness.ui',
  );
}
